// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeMr404ZPECpzVUlU0rLY2bhyo5mtsiwk',
    appId: '1:640025630782:web:5ce2534503798444be596f',
    messagingSenderId: '640025630782',
    projectId: 'ppua-98c49',
    authDomain: 'ppua-98c49.firebaseapp.com',
    storageBucket: 'ppua-98c49.firebasestorage.app',
    measurementId: 'G-W2QJQF5SNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiisyQ7u3-RY-HpfYfrlfHqQ0ugcNJLOE',
    appId: '1:640025630782:android:9ed213051b44365bbe596f',
    messagingSenderId: '640025630782',
    projectId: 'ppua-98c49',
    storageBucket: 'ppua-98c49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBN_nnRYHx2NEjfi8F1FxsdKj73gjfRtM',
    appId: '1:640025630782:ios:5183f531fb7d3c47be596f',
    messagingSenderId: '640025630782',
    projectId: 'ppua-98c49',
    storageBucket: 'ppua-98c49.firebasestorage.app',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBN_nnRYHx2NEjfi8F1FxsdKj73gjfRtM',
    appId: '1:640025630782:ios:5183f531fb7d3c47be596f',
    messagingSenderId: '640025630782',
    projectId: 'ppua-98c49',
    storageBucket: 'ppua-98c49.firebasestorage.app',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeMr404ZPECpzVUlU0rLY2bhyo5mtsiwk',
    appId: '1:640025630782:web:307171c56f1d074abe596f',
    messagingSenderId: '640025630782',
    projectId: 'ppua-98c49',
    authDomain: 'ppua-98c49.firebaseapp.com',
    storageBucket: 'ppua-98c49.firebasestorage.app',
    measurementId: 'G-676H674PP3',
  );
}
